//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntProgFinalProject.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjeOdeviEntities : DbContext
    {
        public ProjeOdeviEntities()
            : base("name=ProjeOdeviEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLAPPLICATIONS> TBLAPPLICATIONS { get; set; }
        public virtual DbSet<TBLCOMPANIES> TBLCOMPANIES { get; set; }
        public virtual DbSet<TBLFAVORITES> TBLFAVORITES { get; set; }
        public virtual DbSet<TBLJOBOPENINGS> TBLJOBOPENINGS { get; set; }
        public virtual DbSet<TBLUSERLOGIN> TBLUSERLOGIN { get; set; }
        public virtual DbSet<TBLUSERS> TBLUSERS { get; set; }
        public virtual DbSet<TBLRESUMES> TBLRESUMES { get; set; }
    }
}
