//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntProgFinalProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAPPLICATIONS
    {
        public int ApplicationID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> Applicationstatus { get; set; }
    
        public virtual TBLCOMPANIES TBLCOMPANIES { get; set; }
        public virtual TBLJOBOPENINGS TBLJOBOPENINGS { get; set; }
        public virtual TBLUSERS TBLUSERS { get; set; }
    }
}
