//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntProgFinalProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFAVORITES
    {
        public int FavoriteID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> JobID { get; set; }
    }
}
