//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntProgFinalProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLJOBOPENINGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLJOBOPENINGS()
        {
            this.TBLAPPLICATIONS = new HashSet<TBLAPPLICATIONS>();
        }
    
        public int ID { get; set; }
        public string Header { get; set; }
        public Nullable<int> Owner { get; set; }
        public string About { get; set; }
        public string Photo { get; set; }
        public string Category { get; set; }
        public string Sector { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLAPPLICATIONS> TBLAPPLICATIONS { get; set; }
        public virtual TBLCOMPANIES TBLCOMPANIES { get; set; }
    }
}
