//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntProgFinalProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRESUMES
    {
        public int OzgecmisID { get; set; }
        public string OzgecmicSahip { get; set; }
        public string OzgecmicDosya { get; set; }
    }
}
